(cl:defpackage robot_tutorial-srv
  (:use )
  (:export
   "IMAGEANGLE"
   "<IMAGEANGLE-REQUEST>"
   "IMAGEANGLE-REQUEST"
   "<IMAGEANGLE-RESPONSE>"
   "IMAGEANGLE-RESPONSE"
   "ODDEVENCHECK"
   "<ODDEVENCHECK-REQUEST>"
   "ODDEVENCHECK-REQUEST"
   "<ODDEVENCHECK-RESPONSE>"
   "ODDEVENCHECK-RESPONSE"
  ))

