// Generated by gencpp from file robot_tutorial/ImageAngle.msg
// DO NOT EDIT!


#ifndef ROBOT_TUTORIAL_MESSAGE_IMAGEANGLE_H
#define ROBOT_TUTORIAL_MESSAGE_IMAGEANGLE_H

#include <ros/service_traits.h>


#include <robot_tutorial/ImageAngleRequest.h>
#include <robot_tutorial/ImageAngleResponse.h>


namespace robot_tutorial
{

struct ImageAngle
{

typedef ImageAngleRequest Request;
typedef ImageAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageAngle
} // namespace robot_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_tutorial::ImageAngle > {
  static const char* value()
  {
    return "47c5200135a81b50accd1b76873c2166";
  }

  static const char* value(const ::robot_tutorial::ImageAngle&) { return value(); }
};

template<>
struct DataType< ::robot_tutorial::ImageAngle > {
  static const char* value()
  {
    return "robot_tutorial/ImageAngle";
  }

  static const char* value(const ::robot_tutorial::ImageAngle&) { return value(); }
};


// service_traits::MD5Sum< ::robot_tutorial::ImageAngleRequest> should match
// service_traits::MD5Sum< ::robot_tutorial::ImageAngle >
template<>
struct MD5Sum< ::robot_tutorial::ImageAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_tutorial::ImageAngle >::value();
  }
  static const char* value(const ::robot_tutorial::ImageAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_tutorial::ImageAngleRequest> should match
// service_traits::DataType< ::robot_tutorial::ImageAngle >
template<>
struct DataType< ::robot_tutorial::ImageAngleRequest>
{
  static const char* value()
  {
    return DataType< ::robot_tutorial::ImageAngle >::value();
  }
  static const char* value(const ::robot_tutorial::ImageAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_tutorial::ImageAngleResponse> should match
// service_traits::MD5Sum< ::robot_tutorial::ImageAngle >
template<>
struct MD5Sum< ::robot_tutorial::ImageAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_tutorial::ImageAngle >::value();
  }
  static const char* value(const ::robot_tutorial::ImageAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_tutorial::ImageAngleResponse> should match
// service_traits::DataType< ::robot_tutorial::ImageAngle >
template<>
struct DataType< ::robot_tutorial::ImageAngleResponse>
{
  static const char* value()
  {
    return DataType< ::robot_tutorial::ImageAngle >::value();
  }
  static const char* value(const ::robot_tutorial::ImageAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_TUTORIAL_MESSAGE_IMAGEANGLE_H
