// Generated by gencpp from file robot_tutorial/ImageAngleRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_TUTORIAL_MESSAGE_IMAGEANGLEREQUEST_H
#define ROBOT_TUTORIAL_MESSAGE_IMAGEANGLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_tutorial
{
template <class ContainerAllocator>
struct ImageAngleRequest_
{
  typedef ImageAngleRequest_<ContainerAllocator> Type;

  ImageAngleRequest_()
    : angle(0)  {
    }
  ImageAngleRequest_(const ContainerAllocator& _alloc)
    : angle(0)  {
  (void)_alloc;
    }



   typedef int32_t _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImageAngleRequest_

typedef ::robot_tutorial::ImageAngleRequest_<std::allocator<void> > ImageAngleRequest;

typedef boost::shared_ptr< ::robot_tutorial::ImageAngleRequest > ImageAngleRequestPtr;
typedef boost::shared_ptr< ::robot_tutorial::ImageAngleRequest const> ImageAngleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_tutorial::ImageAngleRequest_<ContainerAllocator1> & lhs, const ::robot_tutorial::ImageAngleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_tutorial::ImageAngleRequest_<ContainerAllocator1> & lhs, const ::robot_tutorial::ImageAngleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de62f7ef8463d5c42dacb6932cbd1470";
  }

  static const char* value(const ::robot_tutorial::ImageAngleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde62f7ef8463d5c4ULL;
  static const uint64_t static_value2 = 0x2dacb6932cbd1470ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_tutorial/ImageAngleRequest";
  }

  static const char* value(const ::robot_tutorial::ImageAngleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 angle\n"
;
  }

  static const char* value(const ::robot_tutorial::ImageAngleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageAngleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_tutorial::ImageAngleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_tutorial::ImageAngleRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_TUTORIAL_MESSAGE_IMAGEANGLEREQUEST_H
